### ISSUE TITLE
error when importing swim workout

### ISSUE THREAD

**Issue by davidwul** [scrapper/postrunner#10]
I have an error since last update when importing swim workout.
Here is the detail:
ERROR: nil can't be coerced into Float
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivitySummary.rb:310:in `+'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivitySummary.rb:310:in `block (2 levels) in gather_hr_zones'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivitySummary.rb:310:in `each'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivitySummary.rb:310:in `block in gather_hr_zones'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivitySummary.rb:306:in `each'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivitySummary.rb:306:in `gather_hr_zones'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivitySummary.rb:231:in `hr_zones'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivitySummary.rb:57:in `to_html'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivityView.rb:78:in `block (4 levels) in generate_html'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/HTMLBuilder.rb:124:in `create_node'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/HTMLBuilder.rb:89:in `method_missing'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivityView.rb:73:in `block (3 levels) in generate_html'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/HTMLBuilder.rb:124:in `create_node'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/HTMLBuilder.rb:89:in `method_missing'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivityView.rb:72:in `block (2 levels) in generate_html'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/HTMLBuilder.rb:65:in `body'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivityView.rb:70:in `block in generate_html'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/View.rb:41:in `body'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivityView.rb:69:in `generate_html'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/ActivityView.rb:47:in `initialize'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/FFS_Activity.rb:247:in `new'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/FFS_Activity.rb:247:in `generate_html_report'
/var/lib/gems/2.3.0/gems/perobs-4.0.0/lib/perobs/ObjectBase.rb:57:in `method_missing'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/FitFileStore.rb:118:in `add_fit_file'
/var/lib/gems/2.3.0/gems/perobs-4.0.0/lib/perobs/ObjectBase.rb:57:in `method_missing'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/Main.rb:484:in `import_fit_file'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/Main.rb:464:in `process_file'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/Main.rb:449:in `block in process_files'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/Main.rb:443:in `each'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/Main.rb:443:in `process_files'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/Main.rb:347:in `execute_command'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner/Main.rb:77:in `main'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner.rb:24:in `<module:PostRunner>'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/lib/postrunner.rb:22:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/postrunner-0.9.0/bin/postrunner:4:in `<top (required)>'
/usr/local/bin/postrunner:22:in `load'
/usr/local/bin/postrunner:22:in `<main>'

I did not use HR on this one.
If needed, I can send you the fit file per email.

**Comment by scrapper** [comment]
I think I fixed that issue some time ago. But thanks for reporting!
