### ISSUE TITLE
Cant install rspec 3.4.1

### ISSUE THREAD

**Issue by stadelmanma** [scrapper/postrunner#11]
Hi I am going to try and use this gem to manage my Garmin watch although I ran into an error doing bundle install, it couldn't find the gem rspec 3.4.1. 
`Could not find gem 'rspec (~> 3.4.1)' in any of the gem sources listed in your Gemfile.`

I did a simple tweak to the gem spec and it fixed the issue `spec.add_development_dependency 'rspec', '~> 3.4'`

**Comment by scrapper** [comment]
Thanks for the feedback. I'm actually already using version 3.6. I've updated the spec file accordingly.
