### ISSUE TITLE
cycling activity with a new device (edge 530)

### ISSUE THREAD

**Issue by davidwul** [scrapper/postrunner#15]
I tried to import a cycling activity with a new device. There are a lot of warning. But it finally failed with:
`ERROR: undefined method `max_hr' for #<Fit4Ruby::UserProfile:0x000055aa026075c8>`

I can send you the original fit file if you want. Or provide more/other details.

Thanks and tell me if I can do anything, 
David

**Comment by scrapper** [comment]
Please send me the file to <chris> at <taskjuggler> dot <org>. Thanks!
