### ISSUE TITLE
undefined "max_hr"

### ISSUE THREAD

**Issue by davidwul** [scrapper/postrunner#17]

**Comment by davidwul** [comment]
I imported a running activity today and an error occured. 
`ERROR: undefined method `max_hr' for #<Fit4Ruby::UserProfile:0x0000560d3b4a9cc0>`
there are also a lot of unknown field, but that's just warning. The error seems to be from this max_hr.
Any idea where the problem lies... 

Thanks,

**Comment by scrapper** [comment]
Looks like sometimes the HR data in the FIT file contains wholes. This confused the HR max calculation. I've added a fix for that a few weeks ago. Please pull the latest git version and give it a try. It should also eliminate the warnings.
