### ISSUE TITLE
Forerunner 45

### ISSUE THREAD

**Issue by gleporeNARA** [scrapper/postrunner#19]
Just a head's up that the GPS downloader doesn't work with a Garmin Forerunner 45. The difference appears to be in the size of the EPO.BIN file, which is called CPE.BIN on the 45. My sync'ed CPE.BIN file is 1024 bytes shorter than the EPO.BIN file downloaded by postrunner. Unfortunately I don't know enough to figure out how to make it work on the FR45.

**Comment by gleporeNARA** [comment]
Forerunner 45 CPE.BIN file for comparison.
[CPE.BIN.tar.gz](https://github.com/scrapper/postrunner/files/3825110/CPE.BIN.tar.gz)

**Comment by scrapper** [comment]
The EPO.bin file is only compatible with watches that have certain Mediatek GPS chipsets. If your watch does not have such a Mediatek chipset then the EPO.bin download and install process will not work for you. Unfortunately, I have no information on how to download and decode the CPE.bin file. Without that, I can't add support for those devices.
