### ISSUE TITLE
[Garmin Forerunner 35] ERROR: Fit entity has no device info section

### ISSUE THREAD

**Issue by taziden** [scrapper/postrunner#22]
Hi, since 1.0.2, I'm unable to import activites from my Forerunner 35.
For each activity, I have the following error message: "Fit entity has no device info section".

Let me know if more info is needed.
Thanks.

**Comment by scrapper** [comment]
Thanks a lot for the report! Can you give the latest version from the git repository a try, please?

**Comment by taziden** [comment]
Still the same unfortunately. Would it be helpful if I provided a FIT file generated by the FR35?

**Comment by scrapper** [comment]
Yes, this would definitely help!

**Comment by taziden** [comment]
Here is a sample file attached (gzipped because of github restriction).
[A8VK2928.FIT.gz](https://github.com/scrapper/postrunner/files/5151973/A8VK2928.FIT.gz)

**Comment by scrapper** [comment]
Can you try with fit4ruby 3.7.0, please? This hopefully fixes the issue.

**Comment by taziden** [comment]
I can confirm it works perfectly with fit4ruby 3.7.0! Thanks!
I had to manually edit postrunner-1.0.2.gemspec because it explicitly requires fit4ruby 3.6.0.

**Comment by scrapper** [comment]
Great to hear! The gemspec update is now included in postrunner 1.0.3.
