### ISSUE TITLE
upgrade of the PEROBS database is not supported

### ISSUE THREAD

**Issue by ngiger** [scrapper/postrunner#24]
I have a postrunner installation with a database last access in 2019 (when I bought my Forerunner 945).
As it did not support a USB FAT file system I used non-free software to access its data.
I tried to import today an activity after having installed on my debian buster `sudo apt install go-mtp mtp-tools jmtpfs`.
Added `/etc/udev/rules.d/51-garmin.rules` with a line 
`ATTRS{idVendor}=="091e", ATTRS{idProduct}=="0003", MODE="666"`
After un-and replugging my forerunner 945 I was able to access the data.
`sudo mtp-detect` showed the device and `jmtpfs  /tmp/forerunner` mounted it via fuse.
Then I removed the pinning of the bundler gem in postrunner.gemspec and ran successfully bundle install.
However running `bundle exec ruby bin/postrunner import /tmp/forerunner/Primary/GARMIN/Activity/`
failed and gave the following output

```ERROR: The upgrade of this version of the PEROBS database is not supported by this version of PEROBS. Please try an earlier version of PEROBS to upgrade the database before using this version.
/mnt/librem/src/postrunner/vendor/ruby/2.5.0/gems/perobs-4.2.0/lib/perobs/Log.rb:107:in `fatal'
/mnt/librem/src/postrunner/vendor/ruby/2.5.0/gems/perobs-4.2.0/lib/perobs/FlatFileDB.rb:249:in `check_version_and_upgrade'
/mnt/librem/src/postrunner/vendor/ruby/2.5.0/gems/perobs-4.2.0/lib/perobs/FlatFileDB.rb:65:in `initialize'
/mnt/librem/src/postrunner/vendor/ruby/2.5.0/gems/perobs-4.2.0/lib/perobs/Store.rb:154:in `new'
/mnt/librem/src/postrunner/vendor/ruby/2.5.0/gems/perobs-4.2.0/lib/perobs/Store.rb:154:in `initialize'
/mnt/librem/src/postrunner/lib/postrunner/Main.rb:59:in `new'
/mnt/librem/src/postrunner/lib/postrunner/Main.rb:59:in `main'
/mnt/librem/src/postrunner/lib/postrunner.rb:24:in `<module:PostRunner>'
/mnt/librem/src/postrunner/lib/postrunner.rb:22:in `<top (required)>'
bin/postrunner:4:in `require'
bin/postrunner:4:in `<main>'

*******************************************************************************
You have triggered a bug in PostRunner 1.0.3!```

Can you give me a hint on howto resolve this problem. Moving the old directory out of the way resolved the problem! But I would like to preserve the old data. And other people might run into this problem, too.

**Comment by scrapper** [comment]
Please try the just released version 1.0.4 (includes updates of perobs and fit4ruby). It should fix the issue.
