### ISSUE TITLE
import FIT file failed

### ISSUE THREAD

**Issue by davidwul** [scrapper/postrunner#4]
Trying to import a swimming session there is an error:
"ERROR: Checksum error in file 'D:\GARMIN\ACTIVITY\68T62508.FIT'. Computed 6674 instead of 2271."

I tried importing on garmin connect and had no issue. What can I do/provide?

Thanks

**Comment by scrapper** [comment]
Either the file is just slightly corrupt and GC ignores the problem. Or you are using the HRM Swim belt that transfers the data after the swim. The data gets somehow appended at the end. I've never seen such a FIT file, so I'm not sure if that breaks the existing format. If you don't mind sharing the FIT file, please send it to chris <at> linux.com and I'll have a look.

**Comment by davidwul** [comment]
Right I'm using HRM-TRI. I will send you the fit file soon.

**Comment by scrapper** [comment]
Ok, fixed in version 1.4.0. Still cannot decode the data from the HRM-Swim or HRM-Tri that gets appended. No documentation available.
