### ISSUE TITLE
uninitialized constant PEROBS::FlatFileDB

### ISSUE THREAD

**Issue by davidwul** [scrapper/postrunner#5]
Hello, 

I just install postrunner on a new host, when trying to do anything, I got this error:

ERROR: uninitialized constant PEROBS::FlatFileDB

Is there something that changed with the 0.7 version?

**Comment by scrapper** [comment]
Which version of the perobs gem do you have installed? It should be 2.3.1. Looks like the gemspec is still calling for 2.2. I'll fix that.

**Comment by davidwul** [comment]
I just installed now, the new version 
there is no .postrunner files for now.

here are the gems installed:
bigdecimal (1.3.0, 1.2.8)
bindata (2.3.5, 2.1.0)
did_you_mean (1.0.0)
fit4ruby (1.4.0, 1.3.0)
io-console (0.4.6, 0.4.5)
json (2.0.3, 1.8.3)
mini_portile2 (2.1.0)
minitest (5.10.1, 5.9.0)
net-telnet (0.1.1)
nokogiri (1.7.0.1)
perobs (2.3.1)
postrunner (0.7.1, 0.7.0)
power_assert (1.0.1, 0.2.7)
psych (2.2.2, 2.0.17)
rake (12.0.0, 10.5.0)
rdoc (5.0.0, 4.2.1)
test-unit (3.2.3, 3.1.7)

**Comment by scrapper** [comment]
Why do you think that's a problem? .postrunner is a directory that will be created in your home directory if it doesn't exist.

**Comment by davidwul** [comment]
No problem at all. It's just to mention it's a fresh install and the problem does not come from the data in the postrunner directory. Amy idea where the problem could lie or can I enable more log to uncover the issue?

**Comment by marchom** [comment]
Yup. perobs 2.3.1 installed. Experiencing the same issue with latest postrunner 0.7.1 Thanks for the attention.

**Comment by scrapper** [comment]
Can you please try with PEROBS version 2.4.0?

**Comment by davidwul** [comment]
the error is different now:

postrunner --version
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- perobs/Store (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /var/lib/gems/2.3.0/gems/perobs-2.4.0/lib/perobs.rb:29:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/postrunner-0.7.1/lib/postrunner/Main.rb:15:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/postrunner-0.7.1/lib/postrunner.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/postrunner-0.7.1/bin/postrunner:4:in `<top (required)>'
        from /usr/local/bin/postrunner:23:in `load'
        from /usr/local/bin/postrunner:23:in `<main>'

**Comment by marchom** [comment]
Ok It works for me with perobs 2.4.0. Map is showing and all looks good. The one thing I had to do (a bit hacky) is to rename my perobs-2.4.0 gem folder to perobs-2.3.1 because that's the only version postrunner will accept. So perhaps the next release will just bump the dependency?
Thanks!

**Comment by scrapper** [comment]
Thanks for the confirmation. I've just released postrunner 0.7.2 which requires perobs 2.4.0. A postrunner gem install should now just work.

**Comment by davidwul** [comment]
It's working here also after doing a chmod a+r on perobs, fit4ruby and postrunner folders.
By the way, postrunner 0.7.2 install fit4ruby 1.3.0
Is it something on purpose not to use 1.4.0 version?

**Comment by scrapper** [comment]
No, that should be fit4ruby 1.4.0. Albeit the difference is pretty small. I'll fix that in the next release. Thanks for the hint!
